<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ambil_bahan_model extends CI_Model
{

    public $table = 'ambil_bahan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('ambil_bahan.id as id, detail_spk.no_spk  as no_spk, bahan_rendam.kolam as kolam , tgl_keluar , ambil_bahan.kg as kg , ambil_bahan.ball as ball,nama_sopir');
        $this->datatables->from('ambil_bahan');
        //add this line for join
        $this->datatables->join('bahan_rendam', 'ambil_bahan.id_bahan_rendam = bahan_rendam.id');
        $this->datatables->join('detail_spk', 'ambil_bahan.id_detail_spk = detail_spk.id');
        $this->datatables->add_column('action', anchor(site_url('ambil_bahan/read/$1'), 'Read') . " | " . anchor(site_url('ambil_bahan/update/$1'), 'Update') . " | " . anchor(site_url('ambil_bahan/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_detail_spk', $q);
        $this->db->or_like('id_bahan_rendam', $q);
        $this->db->or_like('tgl_keluar', $q);
        $this->db->or_like('kg', $q);
        $this->db->or_like('ball', $q);
        $this->db->or_like('nama_sopir', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('id_detail_spk', $q);
        $this->db->or_like('id_bahan_rendam', $q);
        $this->db->or_like('tgl_keluar', $q);
        $this->db->or_like('kg', $q);
        $this->db->or_like('ball', $q);
        $this->db->or_like('nama_sopir', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function lihatkolam()
    {
        return $this->db->query("select * from bahan_rendam join bahan on bahan_rendam.id_bahan = bahan.id")->result_array();
    }
    function lihatnospk()
    {
        return $this->db->query("select * from detail_spk")->result_array();
    }
}

/* End of file Ambil_bahan_model.php */
/* Location: ./application/models/Ambil_bahan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-22 13:29:43 */
/* http://harviacode.com */