<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bahan_masuk_model extends CI_Model
{

    public $table = 'bahan_masuk';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function jsonIsAdmin()
    {
        $this->datatables->select('bahan_masuk.id as id,bahan.id as idbahan, id_bahan,tgl_masuk,ball,kg,asal_bahan');
        $this->datatables->from('bahan_masuk');
        //add this line for join
        $this->datatables->join('bahan', 'bahan_masuk.id_bahan = bahan.id');
        $this->datatables->add_column('action', anchor(site_url('bahan_masuk/read/$1'), 'Read') . " | " . anchor(site_url('bahan_masuk/update/$1'), 'Update') . " | " . anchor(site_url('bahan_masuk/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }
    function json()
    {
        $this->datatables->select('bahan_masuk.id as id,bahan.id as idbahan, id_bahan,tgl_masuk,ball,kg,asal_bahan');
        $this->datatables->from('bahan_masuk');
        //add this line for join
        $this->datatables->join('bahan', 'bahan_masuk.id_bahan = bahan.id');
        $this->datatables->add_column('action', anchor(site_url('bahan_masuk/read/$1'), 'Read'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_bahan', $q);
        $this->db->or_like('tgl_masuk', $q);
        $this->db->or_like('kg', $q);
        $this->db->or_like('ball', $q);
        $this->db->or_like('asal_bahan', $q);
        $this->db->or_like('ket', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('id_bahan', $q);
        $this->db->or_like('tgl_masuk', $q);
        $this->db->or_like('kg', $q);
        $this->db->or_like('ball', $q);
        $this->db->or_like('asal_bahan', $q);
        $this->db->or_like('ket', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function lihatbahan()
    {
        return $this->db->query("select * from bahan")->result_array();
    }
}

/* End of file Bahan_masuk_model.php */
/* Location: ./application/models/Bahan_masuk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-22 13:29:43 */
/* http://harviacode.com */