<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pabrikqc_model extends CI_Model
{

    public $table = 'qc';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function lihatspk2($pabrik)
    {
        return $this->db->query("select spk.no_spk as no_spk, 
                                po_pabrik.id_pabrik as id_pabrik, 
                                detail_spk.no_item as no_item, 
                                spk.status as status,
                                spk.id_sub as id_sub,
                                spk.tgl_mulai as tgl_mulai,
                                spk.tgl_selesai as tgl_selesai,
                                detail_spk.id as id,
                                detail_spk.total_qty as total_qty
                                from spk 
                                join detail_spk on spk.no_spk = detail_spk.no_spk 
                                join po_pabrik on spk.id_po_pabrik = po_pabrik.id
                                where status = 'Belum Selesai' && id_pabrik= $pabrik")->result();
    }
    function lihatspk()
    {
        return $this->db->query("select * from spk 
                                join detail_spk where spk.no_spk = detail_spk.no_spk ")->result();
    }
    function input_data($data, $table)
    {
        $this->db->insert($table, $data);
    }
    function lihatspkperid($id)
    {
        $this->db->where('id', $id);
        return $this->db->get('detail_spk')->row();
    }
}


/* End of file Pabrik_model.php */
/* Location: ./application/models/Pabrik_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-03-19 11:59:24 */
/* http://harviacode.com */