<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Simpan_model extends CI_Model
{

    public $table = 'simpan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('simpan.id as id, penyimpanan.no_item as no_item, qty, tgl');
        $this->datatables->from('simpan');
        //add this line for join
        $this->datatables->join('penyimpanan', 'simpan.no_item = penyimpanan.no_item');
        $this->datatables->add_column('action', anchor(site_url('simpan/read/$1'), 'Read') . " | " . anchor(site_url('simpan/update/$1'), 'Update') . " | " . anchor(site_url('simpan/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('no_item', $q);
        $this->db->or_like('qty', $q);
        $this->db->or_like('tgl', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('no_item', $q);
        $this->db->or_like('qty', $q);
        $this->db->or_like('tgl', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function lihatpenyimpanan()
    {
        return $this->db->query("select * from penyimpanan")->result_array();
    }
}

/* End of file Simpan_model.php */
/* Location: ./application/models/Simpan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-22 13:29:43 */
/* http://harviacode.com */